version: "3.8"


services:
  database:
    container_name: openaidatabase
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=opensecret
      - POSTGRES_DB=openai
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data 

volumes:
  db: